Opetushallitus/jod-ohjaaja-ui

vite.config.ts
- Update base
https://jira.eduuni.fi/browse/OPHJOD-1053
=> OPHJOD-1053: Update base

.github/workflows/build.yml, .github/workflows/deploy.yml
- Add deployment workflows
https://jira.eduuni.fi/browse/OPHJOD-1065
=> OPHJOD-1065: Add deployment workflows

package-lock.json, package.json, src/components/LanguageMenu/LanguageMenu.tsx, src/components/NavigationBar/NavigationBar.test.tsx, src/hooks/useLocalizedRoutes/useLocalizedRoutes.test.tsx, src/hooks/useLocalizedRoutes/useLocalizedRoutes.tsx, src/hooks/useLoginLink/index.ts, src/main.tsx, src/routes/Home/Home.tsx, src/routes/Root/Root.tsx, src/routes/index.tsx
- Upgrade react-router to version 7
https://jira.eduuni.fi/browse/OPHJOD-1117
=> OPHJOD-1117: Upgrade react-router to version 7

eslint.config.js, package-lock.json, package.json, src/routes/Root/NoMatch.tsx
* Update eslint-plugin-sonarjs
* No more peer dependency errors during `npm install` 🎉
* Some rule changes were necessary, possibly due to this change mentioned in [sonarjs plugin changelog](https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/CHANGELOG.md):
* `Remove decorated rules from ESLint plugin`
https://jira.eduuni.fi/browse/OPHJOD-1116
=> OPHJOD-1116: Update eslint-plugin-sonarjs

src/routes/ContentDetails/loader.ts, src/routes/Home/loader.ts, vite.config.ts
Change CMS endpoint to `/ohjaaja/cms`
https://jira.eduuni.fi/browse/OPHJOD-1138
=> OPHJOD-1138: Change CMS endpoint

index.html, package-lock.json, package.json, vite.config.ts
- Update Vitest
https://jira.eduuni.fi/browse/OPHJOD-1108
=> OPHJOD-1108: Update Vitest

package-lock.json, src/i18n/fi/translation.json, src/routes/Home/Home.tsx
* Update DS
* Use CardCarousel component
* Change main layout padding on home page to always be 16px (`px-5`)
https://jira.eduuni.fi/browse/OPHJOD-1203
=> OPHJOD-1203: Update DS and implement CardCarousel component

package-lock.json
- Use updated footer
https://jira.eduuni.fi/browse/OPHJOD-1210
=> OPHJOD-1210: Use updated footer

src/routes/ContentDetails/ContentDetails.tsx, src/routes/Home/Home.tsx, src/utils/cms.ts
* Finds content by a name instead of a label
* Added some more stylings for rich text content
https://jira.eduuni.fi/browse/OPHJOD-1237
=> OPHJOD-1237: Find content by a name instead of a label

.vscode/launch.json, README.md, vite.config.ts
- Update application to run on port 8180
https://jira.eduuni.fi/browse/OPHJOD-1247
=> OPHJOD-1247: Update application to run on port 8180

src/components/MegaMenu/MegaMenu.tsx, src/hooks/useMenuClickHandler/index.ts, src/i18n/fi/translation.json, src/routes/Root/Root.tsx, src/routes/Root/index.ts, src/routes/Root/loader.test.ts, src/routes/Root/loader.ts, src/routes/index.tsx
- Adds language selector to top bar / main menu
- Implementation is mostly copied from jod-yksilo-ui
https://jira.eduuni.fi/browse/OPHJOD-1252
=> OPHJOD-1252: Implement language selection

package-lock.json, package.json, src/components/ContentList/ContentList.tsx, src/hooks/useCategoryContentListLoader/index.ts, src/i18n/fi/translation.json, src/routes/CategoryContent/CategoryContent.tsx, src/routes/CategoryContent/index.ts, src/routes/Home/Home.tsx, src/routes/index.tsx
- Adds first draft of the content listing view
- Note that
- Has a page size of two so we can see "Näytä lisää" button in action
- Is linked only to Tietosisällöt 
https://jira.eduuni.fi/browse/OPHJOD-1253
=> OPHJOD-1253: Add content listing view

src/i18n/fi/translation.json, src/routes/ContentDetails/ContentDetails.tsx
Added modified date to article
https://jira.eduuni.fi/browse/OPHJOD-1295
=> OPHJOD-1295: Add modified date to article

src/routes/ContentDetails/ContentDetails.tsx, src/utils/cms.ts
- Display embedded Youtube videos
https://jira.eduuni.fi/browse/OPHJOD-1294
=> OPHJOD-1294: Show embedded Youtube videos

index.html, package-lock.json, src/components/FeatureCard/FeatureCard.tsx, src/i18n/fi/translation.json, src/routes/Home/Home.tsx, src/routes/Root/Root.tsx
- Add FeatureCard and update home view
https://jira.eduuni.fi/browse/OPHJOD-1289
=> OPHJOD-1289: Add FeatureCard and update home view

src/routes/Home/Home.tsx
- Fix hero image source
https://jira.eduuni.fi/browse/OPHJOD-1289
=> OPHJOD-1289: Fix hero image source

.github/workflows/deploy.yml
Remove cloudfront cache invalidation from deploy
https://jira.eduuni.fi/browse/OPHJOD-1234
=> OPHJOD-1234: Remove cache invalidation

package-lock.json
- Update DS
https://jira.eduuni.fi/browse/OPHJOD-1293
=> OPHJOD-1293: Update DS

package-lock.json
- Update DS
https://jira.eduuni.fi/browse/OPHJOD-1320
=> OPHJOD-1320: Update DS

src/routes/Home/Home.tsx
- Refactor carousel styling
https://jira.eduuni.fi/browse/OPHJOD-1293
=> OPHJOD-1293: Refactor carousel styling

src/components/ContentList/ContentList.tsx, src/routes/ContentDetails/loader.ts, src/routes/Home/Home.tsx, src/routes/index.tsx, src/services/cms-api.ts, src/services/navigation-loader.ts, src/types/cms-navigation.ts, src/utils/navigation-paths.test.ts, src/utils/navigation-paths.ts, src/utils/navigation.test.ts, src/utils/navigation.ts
- Modified navigation structure retrieval to use the new API
https://jira.eduuni.fi/browse/OPHJOD-1338
=> OPHJOD-1338: Modify navigation structure retrieval to use the new API

src/i18n/fi/translation.json, src/routes/ContentDetails/ContentDetails.tsx
- Add Print-button to article page
- Slight adjustments:
- auto hyphens to title to prevent long title breaking the layout on mobile
- adjust gaps to smaller on mobile
- removed the top margin from the first paragraph of the text
https://jira.eduuni.fi/browse/OPHJOD-1316
=> OPHJOD-1316: Add print button to article page

src/components/ContentList/ContentList.tsx, src/services/cms-api.ts, src/types/cms-content.ts, src/utils/cms.test.ts, src/utils/cms.ts
Detect keywords by using embeddedTaxonomyCategory.categoryType to distinguish keyword categories from others
https://jira.eduuni.fi/browse/OPHJOD-1441
=> OPHJOD-1441: Detect keywords by using embeddedTaxonomyCategory.categoryType to distinguish keyword categories from others

package-lock.json, package.json, src/components/ContentList/ContentList.tsx, src/components/SearchResults/SearchResults.tsx, src/hooks/useTags/index.ts, src/hooks/useTags/useTags.ts, src/i18n/en/translation.json, src/i18n/fi/translation.json, src/routes/CategoryContent/CategoryContent.tsx, src/routes/ContentDetails/ContentDetails.tsx, src/routes/Home/Home.tsx, src/routes/Search/Search.tsx, src/routes/Search/TagFilterList.tsx, src/routes/Search/constants.ts, src/routes/Search/index.ts, src/routes/Search/loader.ts, src/routes/index.tsx, src/services/cms-api.ts, src/types/cms-content.ts, src/types/cms-navigation.ts, src/utils/cms.test.ts, src/utils/cms.ts, src/utils/navigation-paths.ts, src/utils/navigation.test.ts, src/utils/navigation.ts
* Tags in MediaCard and ContentCard are now clickable and initiate a search filtered by the selected tag.
* The search view supports free-text search as well as filtering results by tags.
* Finalized mobile layouts are not yet implemented, as the design for mobile is still pending.
https://jira.eduuni.fi/browse/OPHJOD-1472
=> OPHJOD-1472: Add Search view

index.html, package-lock.json, package.json
- Update dependencies
https://jira.eduuni.fi/browse/OPHJOD-1503
=> OPHJOD-1503: Update dependencies

src/components/Breadcrumb/Breadcrumb.tsx, src/components/MainLayout/MainLayout.tsx, src/i18n/fi/translation.json, src/routes/index.tsx
Add Breadcrumb component
https://jira.eduuni.fi/browse/OPHJOD-1499
=> OPHJOD-1499: Add Breadcrumb component

package-lock.json, package.json, src/api/schema.d.ts, src/api/suosikit.ts, src/auth/auth.ts, src/components/ArticleCard/ArticleCard.tsx, src/components/ContentList/ContentList.tsx, src/i18n/fi/translation.json, src/routes/CategoryContent/CategoryContent.tsx, src/routes/CategoryContent/loader.ts, src/routes/ContentDetails/ContentDetails.tsx, src/routes/ContentDetails/loader.ts, src/routes/Home/Home.tsx, src/routes/Home/loader.ts, src/routes/Root/loader.test.ts, src/routes/Root/loader.ts, src/routes/index.tsx, src/stores/useSuosikitStore/index.ts
* Authorized user can now save article as a favorite and remove from the favorites. 
https://jira.eduuni.fi/browse/OPHJOD-1501
=> OPHJOD-1501: Add favorites feature

package-lock.json, src/components/LanguageButton/LanguageButton.tsx, src/components/MegaMenu/MegaMenu.tsx, src/components/UserButton/UserButton.tsx, src/routes/Root/Root.tsx
- Use updated NavigationBar
https://jira.eduuni.fi/browse/OPHJOD-1527
=> OPHJOD-1527: Use updated NavigationBar

src/components/MainLayout/MainLayout.tsx, src/components/NavMenu/NavLinkBasedOnAuth.tsx, src/components/NavMenu/NavMenu.tsx, src/components/NavMenu/menuRoutes.tsx, src/i18n/fi/translation.json, src/routes/Root/Root.tsx
Use new NavigationMenu
https://jira.eduuni.fi/browse/OPHJOD-1558
=> OPHJOD-1558: Use new NavigationMenu

src/components/LanguageButton/LanguageButton.tsx, src/components/UserButton/UserButton.tsx
- Remove redundant ds classes
https://jira.eduuni.fi/browse/OPHJOD-1527
=> OPHJOD-1527: Remove redundant ds classes

src/components/LanguageMenu/LanguageMenu.tsx
- Remove gray bg from langauge menu
https://jira.eduuni.fi/browse/OPHJOD-1527
=> OPHJOD-1527: Remove gray bg from langauge menu

src/api/artikkelinKatselu.ts, src/api/schema.d.ts, src/components/RecentlyWatchedContent/RecentlyWatchedContent.tsx, src/services/cms-api.ts
Fetches the articles most recently viewed by the logged-in user and displays the first four.
https://jira.eduuni.fi/browse/OPHJOD-1565
=> OPHJOD-1565: update to display recently viewed articles

src/components/MainLayout/MainLayout.tsx, src/components/SearchBanner/SearchBanner.tsx, src/i18n/fi/translation.json, src/routes/Category/CategoryMain.tsx, src/routes/Home/Home.tsx, src/routes/Search/Search.tsx
Adds SearchBanner
https://jira.eduuni.fi/browse/OPHJOD-1586
=> OPHJOD-1586: add SearchBanner

package-lock.json, src/components/ArticleCard/ArticleCard.tsx, src/components/ButtonMenu/ButtonMenu.tsx, src/components/CategoryList/CategoryList.tsx, src/components/MainLayout/CategoryNavigation.tsx, src/components/MainLayout/MainLayout.tsx, src/components/MainLayout/NavigationList.tsx, src/components/MainLayout/ProfileNavigation.tsx, src/components/RecentlyWatchedContent/RecentlyWatchedContent.tsx, src/components/SearchResults/SearchResults.tsx, src/components/SuggestNewContent/SuggestNewContent.tsx, src/hooks/useAppRoutes/index.ts, src/i18n/fi/translation.json, src/routes/Category/CategoryMain.tsx, src/routes/ContentDetails/ContentDetails.tsx, src/routes/Home/Home.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/Favorites/index.ts, src/routes/Search/TagFilterList.tsx, src/routes/index.tsx, src/types/cms-content.ts, src/types/sort.ts, src/utils/cms.test.ts, src/utils/cms.ts, src/utils/navigation-paths.test.ts, src/utils/navigation-paths.ts, src/utils/navigation.test.ts, src/utils/navigation.ts
- Implemented Favorites route and component to display user's favorite articles.
- Updated routing to include favorites in the profile section.
- Added sorting functionality for favorites with options for a-z, z-a, latest, oldest, and latest added to favorites.
- Refactored navigation utilities to support new features.
- Created ButtonMenu component 
https://jira.eduuni.fi/browse/OPHJOD-1591
=> OPHJOD-1591: Add favorites feature to user profile

src/components/ButtonMenu/ButtonMenu.tsx, src/components/SearchResults/SearchResults.tsx, src/i18n/fi/translation.json, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Search/Search.tsx, src/routes/Search/TagFilterList.tsx
Update search page
https://jira.eduuni.fi/browse/OPHJOD-1587
=> OPHJOD-1587: Update search page

src/components/SearchResults/SearchResults.tsx
Show pagination only when there are more than one page
https://jira.eduuni.fi/browse/OPHJOD-1599
=> OPHJOD-1599: Fix pagination display logic in SearchResults

src/routes/Home/Home.tsx
Update Homepage link to favorites
https://jira.eduuni.fi/browse/OPHJOD-1622
=> OPHJOD-1622: Update Homepage link to favorites

package-lock.json
Update `@jod/design-system` to get updated **MediaCard**
https://jira.eduuni.fi/browse/OPHJOD-1600
=> OPHJOD-1600: Update @jod/design-system; updated MediaCard

src/components/UserButton/UserButton.tsx, src/i18n/fi/translation.json, src/routes/Profile/Details/Details.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/Preferences/Preferences.tsx, src/routes/index.tsx
Update texts and add some layout mockups
https://jira.eduuni.fi/browse/OPHJOD-1576
=> OPHJOD-1576: Update texts and add some layout mockups

src/components/MainLayout/CategoryNavigation.tsx, src/hooks/useCategoryRoutes/useCategoryRoute.test.ts, src/hooks/useCategoryRoutes/useCategoryRoute.ts, src/routes/Category/CategoryListing.tsx, src/routes/Category/CategoryMain.tsx
- add title and description to category listing page
https://jira.eduuni.fi/browse/OPHJOD-1664
=> OPHJOD-1664: add title and description to category listing page

package-lock.json, package.json
Update outdated dependencies reported by Snyk
Closes #88 
Closes #89 
Closes #90 
Closes #91 
Closes #93 
https://jira.eduuni.fi/browse/OPHJOD-1720
=> OPHJOD-1720: Update dependencies

package-lock.json, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Root/Root.tsx
- Add MatomoTracker
https://jira.eduuni.fi/browse/OPHJOD-1687
=> OPHJOD-1687: Add MatomoTracker

package-lock.json, src/components/NavMenu/NavMenu.tsx, src/components/NavMenu/menuRoutes.tsx, src/components/SearchResults/SearchResults.tsx, src/i18n/fi/translation.json, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Root/ErrorBoundary.tsx, src/routes/Root/NoMatch.tsx
* Update Design System
* Update NavMenu to match design
https://jira.eduuni.fi/browse/OPHJOD-1777
=> OPHJOD-1777: Update DS and NavMenu

src/api/artikkelinKommentit.ts, src/api/schema.d.ts, src/components/Comments/Comment.test.tsx, src/components/Comments/Comment.tsx, src/components/Comments/Comments.tsx, src/i18n/fi/translation.json
OPHJOD-1793: Add comment reporting feature
https://jira.eduuni.fi/browse/OPHJOD-1793
=> OPHJOD-1793: Add comment reporting feature

src/i18n/config.ts
- Update supported languages
https://jira.eduuni.fi/browse/OPHJOD-1857
=> OPHJOD-1857: Update supported languages

src/routes/Root/Root.tsx
- Update chatbot agents
https://jira.eduuni.fi/browse/OPHJOD-1882
=> OPHJOD-1882: Update chatbot agents

package-lock.json
- Update DS
https://jira.eduuni.fi/browse/OPHJOD-1882
=> OPHJOD-1882: Update DS

src/api/features.ts, src/api/schema.d.ts, src/hooks/useFeatures/useFeatures.ts, src/routes/ContentDetails/ContentDetails.tsx, src/types/feature.ts
Add feature toggle for comments functionality
https://jira.eduuni.fi/browse/OPHJOD-1828
=> OPHJOD-1828: Add feature toggle for comments functionality

src/components/NavMenu/menuRoutes.tsx
Fix navigation link path
https://jira.eduuni.fi/browse/OPHJOD-1910
=> OPHJOD-1910: Fix navigation link path

package-lock.json, src/routes/Profile/Favorites/Favorites.tsx
- Fix issue where the last favorite did not disappear from the list after removal
- Update design system dependency
https://jira.eduuni.fi/browse/OPHJOD-1950
=> OPHJOD-1950: Fix issue where the last favorite did not disappear from the list after removal

src/routes/Category/CategoryMain.tsx, src/routes/Home/Home.tsx
Reorder carousels. Show popular before latest in all views
https://jira.eduuni.fi/browse/OPHJOD-1986
=> OPHJOD-1986: Reorder carousels. Show popular before latest in all views

src/components/NavMenu/menuRoutes.tsx
Fix navigation menu. 
https://jira.eduuni.fi/browse/OPHJOD-1991
=> OPHJOD-1991: Fix navigation menu

src/api/middlewares/sessionExpired.ts, src/auth/auth.ts, src/auth/index.ts, src/components/CategoryList/CategoryList.tsx, src/components/Comments/Comments.tsx, src/components/UserButton/UserButton.tsx, src/routes/Category/CategoryListing.tsx, src/routes/Category/CategoryMain.tsx, src/routes/Category/loader.ts, src/routes/ContentDetails/ContentDetails.tsx, src/routes/ContentDetails/loader.ts, src/routes/Home/Home.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Root/Root.tsx, src/routes/index.tsx, src/stores/useAuthStore/index.ts, src/stores/useNoteStore/index.ts, src/types/auth.ts
Refactor authentication handling and session management
- Replace authStore with useAuthStore for better state management.
- Implement session expiration handling in sessionExpiredMiddleware.
- Update components to utilize user state from useAuthStore.
- Introduce useNoteStore for managing error notes.
https://jira.eduuni.fi/browse/OPHJOD-1947
=> OPHJOD-1947: Refactor authentication handling and session management

package-lock.json, package.json
update dependencies
Closes #146 
Closes #145 
Closes #144 
Closes #143 
Closes #142
https://jira.eduuni.fi/browse/OPHJOD-2113
=> OPHJOD-2113: update dependencies

package-lock.json, src/api/middlewares/toast.ts
- Refactor toast middleware to enhance ignored operations handling
- Update Design system
https://jira.eduuni.fi/browse/OPHJOD-2126
=> OPHJOD-2126: Refactor toast middleware

src/components/ArticleCard/ArticleCard.tsx, src/routes/ContentDetails/ContentDetails.tsx, src/utils/cms.ts
Use new fixed image sizes
https://jira.eduuni.fi/browse/OPHJOD-2112
=> OPHJOD-2112: Use new fixed image sizes

src/hooks/useCategoryRoutes/useCategoryRoute.ts, src/routes/Category/CategoryListing.tsx, src/routes/Category/loader.ts, src/routes/index.tsx
Fix missing title and description on StudyProgramListing page
https://jira.eduuni.fi/browse/OPHJOD-2160
=> OPHJOD-2160: Fix missing title and description on StudyProgramListing page

package-lock.json, src/i18n/fi/translation.json, src/routes/Root/Root.tsx
Add beta-feedback banner
https://jira.eduuni.fi/browse/OPHJOD-2284
=> OPHJOD-2284: Add beta-feedback banner

src/components/CategoryList/CategoryList.tsx, src/components/Comments/CommentInput.tsx, src/components/ConfirmDialogWrapper/ConfirmDialogWrapper.tsx, src/components/ContentList/ContentList.tsx, src/components/SuggestNewContentModal/SuggestNewContentModal.tsx, src/components/createLoginDialogFooter.tsx, src/routes/LoginPage/LoginPage.tsx, src/routes/Profile/Preferences/Preferences.tsx
- Fix login page redirects back to front page after session timeout
- Also set service variant to buttons
https://jira.eduuni.fi/browse/OPHJOD-2213
=> OPHJOD-2213: Fix login page redirects back to front page after session timeout

src/api/schema.d.ts, src/components/SuggestNewContentModal/SuggestNewContentModal.tsx, src/i18n/fi/translation.json
Enhance SuggestNewContentModal with form submission handling and content guide
https://jira.eduuni.fi/browse/OPHJOD-2195
=> OPHJOD-2195: Enhance SuggestNewContentModal with form submission handling and content guide

package-lock.json, src/i18n/fi/translation.json, src/routes/Root/Root.tsx
- Update footer information
https://jira.eduuni.fi/browse/OPHJOD-2235
=> OPHJOD-2235: Update footer information

package-lock.json, src/components/NavMenu/NavMenu.tsx, src/i18n/fi/translation.json
Update navigation menu translations, ordering and DS
https://jira.eduuni.fi/browse/OPHJOD-2241
=> OPHJOD-2241: Update navigation menu translations, ordering and DS

src/components/FeatureCard/FeatureCard.tsx, src/i18n/fi/translation.json, src/routes/Home/Home.tsx
Refactor FeatureCard styles and improve Home component layout
https://jira.eduuni.fi/browse/OPHJOD-2079
=> OPHJOD-2079: Refactor FeatureCard styles and improve Home component layout

src/i18n/fi/translation.json, src/routes/Profile/Details/Details.tsx, src/routes/Profile/Favorites/Favorites.tsx, src/routes/Profile/Preferences/Preferences.tsx, src/routes/Profile/ProfileFront/ProfileFront.tsx
update profile texts
https://jira.eduuni.fi/browse/OPHJOD-2374
=> OPHJOD-2374: update profile texts

src/routes/Profile/Details/Details.tsx
Add accessibility attributes to interests section in profile details
https://jira.eduuni.fi/browse/OPHJOD-2084
=> OPHJOD-2084: Add accessibility attributes to interests section in profile details

src/i18n/fi/translation.json
- Fix typos and improve translations
https://jira.eduuni.fi/browse/OPHJOD-2393
=> OPHJOD-2393: Fix typos and improve translations

src/routes/Profile/Preferences/Preferences.tsx
Refactor Preferences component to handle user session expiration
https://jira.eduuni.fi/browse/OPHJOD-2339
=> OPHJOD-2339: Refactor Preferences component to handle user session expiration

package-lock.json, src/components/MainLayout/CategoryNavigation.tsx, src/components/MainLayout/ProfileNavigation.tsx, src/components/SuggestNewContentModal/SuggestNewContentModal.tsx, src/routes/ContentDetails/ContentDetails.tsx, src/routes/Search/TagFilterList.tsx
* Update DS
* Fix wrong heading tag in `ContentDetails`: Additional details title from `h3` -> `h2`
* Update Accordion props since they changed in DS update
https://jira.eduuni.fi/browse/OPHJOD-2119
=> OPHJOD-2119: Fix heading tag in ContentDetails and new Accordion props

src/routes/Category/loader.ts, src/utils/navigation.ts
Fixes most popular content listing on main category page
https://jira.eduuni.fi/browse/OPHJOD-2456
=> OPHJOD-2456: Fix most popular content listing

src/routes/ContentDetails/ContentDetails.tsx
Improve image, header and actions styling in ContentDetails
https://jira.eduuni.fi/browse/OPHJOD-2457
=> OPHJOD-2457: Improve image, header and actions styling in ContentDetails

src/routes/Home/loader.ts, src/services/cms-article-api.ts, src/utils/navigation.ts
Exclude study programs from newest content in front page
https://jira.eduuni.fi/browse/OPHJOD-2458
=> OPHJOD-2458: Exclude study programs from newest content in front page
